services:
  database:
    image: docker.io/postgres:alpine
    container_name: rust-iteration-04-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD-password}"
      POSTGRES_USER: "${POSTGRES_USER-user}"
      POSTGRES_DB: "${POSTGRES_DB-social-network-production}"
    volumes:
      - database-persistence:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: docker.io/adminer:latest
    container_name: rust-iteration-04-database-adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  database-persistence:
