[package]
name = "it02-data-processing"
version = "0.1.0"
edition = "2024"
authors = ["Ondřej Hrdlička"]

[dependencies]
csv = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
chrono = { version = "0.4.42", features = ["serde"] }
itertools = { version = "0.14.0" }
